### ISSUE TITLE
Code reformat style

### ISSUE THREAD

**Issue by kernc** [marcelhillesheim/outSPARQL#2]
When auto-reformatting (_Code > Reformat Code_), the code is formatted according to [some weird style with IMHO far too excessive indentation](https://plugins.jetbrains.com/plugin/16503-outsparql/tutorial/auto-completion) to nest queries. Is there any way to influence code style if I'd like something more like [1TBS](https://en.wikipedia.org/wiki/Indentation_style#Variant:_1TBS_(OTBS))?

Preferences in Pycharm _Settings > Editor > Code Style > SQL_ do not seem to be respected.

Many thanks!

**Comment by marcelhillesheim** [comment]
Ok i know what you mean. I think the problem got introduced with the autocompletion update as that needed autoclosing braces. The Bracematcher seems to force this indent as there is no other formatting rule defined. So the "block" is aligned with the position of the braces.

Fixed this issue (no forced indentations except for where clauses (1 tab))

But i have to implement and test the newline rules. So the prefix quickfixes are properly formatted. I will release an update in the next 1-2 days.

**Comment by marcelhillesheim** [comment]
Update just got approved by jetbrains and is now available for download. This should fix your issue.

Thanks for the report. I am currently not using the plugin myself, but i like to keep improving it. So if you encounter any issues or  have suggestions, feel free to create a new issue.

**Comment by kernc** [comment]
It chokes on [nonstandard `WITH` clause](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/query_optimization#Named_subqueries), but otherwise works way better. Thanks again!

**Comment by marcelhillesheim** [comment]
Ok didnt know that there are extensions for Sparql besides SPARQL Star (BlazeGraph extension).
   https://github.com/blazegraph/database/blob/master/sparql-grammar/src/main/java/com/bigdata/rdf/sail/sparql/ast/sparql.jjt
   
   2000 lines of code for the grammar which i would have to compare with the basic SPARQL 1.1 grammar to add the additional rules. Maybe on a boring weekend :d 
  
  
   
    kernc ***@***.***> hat am 30.08.2021 00:12 geschrieben:
   
   
    
   
   
    
   
   
   It chokes on nonstandard WITH clause, but otherwise works way better. Thanks again!

**Comment by kernc** [comment]
Reformatting also doesn't indent individual values of the `VALUES` block, such as in the following example input:
```sql
SELECT DISTINCT
  ?item
WHERE {
  VALUES ?Products {
    wd:Q2424752  # product
    wd:Q2897903  # goods and services
  }
  ?item wdt:P31/wdt:P279* ?Products
}
LIMIT 100
```
Reformatted output:
```sql
SELECT DISTINCT
?item
WHERE {
    VALUES ?Products {
    wd:Q2424752  # product
    wd:Q2897903  # goods and services
    }
    ?item wdt:P31/wdt:P279* ?Products
}
LIMIT 100
```
