### ISSUE TITLE
Column order ignore projection order in SPARQL window tool

### ISSUE THREAD

**Issue by dereckson** [marcelhillesheim/outSPARQL#3]
When running a query with the help of the SPARQL window tool, the results are correct, but the order of the column follows their order of appearance in the query, not in the SELECT clause:

For example, running this query against Wikidata end-point (https://query.wikidata.org/sparql):

```
PREFIX bd: <http://www.bigdata.com/rdf#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

# Streets with FANTOIR code
SELECT DISTINCT ?code_fantoir ?item ?itemLabel ?what
WHERE
{
  ?item wdt:P3182 ?code_fantoir .
  ?item wdt:P31 ?what
  SERVICE wikibase:label { bd:serviceParam wikibase:language "fr". }
}
```

The WHERE clause order is item code_fantoir, itemLabel. The SELECT clause uses another order.

It prints:

![image](https://user-images.githubusercontent.com/135563/211630339-8c6b9ab0-1e16-4250-9d2e-caf68562daef.png)

We can see the header follows the SELECT clause, but the data follows the WHERE clause order.

**Comment by dereckson** [comment]
I think I've identified the issue: your code expects the end-point to return in a logic order the result, but with the Wikidata end-point, that's not the case:

```
<sparql xmlns='http://www.w3.org/2005/sparql-results#'>
	<head>
		<variable name='code_fantoir'/>
		<variable name='item'/>
		<variable name='itemLabel'/>
		<variable name='what'/>
	</head>
	<results>
		<result>
			<binding name='item'>
				<uri>http://www.wikidata.org/entity/Q849777</uri>
			</binding>
			<binding name='code_fantoir'>
				<literal>755112P144L</literal>
			</binding>
			<binding name='what'>
				<uri>http://www.wikidata.org/entity/Q510662</uri>
			</binding>
			<binding name='itemLabel'>
				<literal xml:lang='fr'>boulevard périphérique de Paris</literal>
			</binding>
		</result>
                ...
	</results>
</sparql>
```

**Comment by marcelhillesheim** [comment]
Sorry for the late answer. This seems to be a critical issue, when this happens with two columns of the same type like integer, where it is not easy to spot. Will try to fix it and update it asap. 

In the mean time i will add a warning to the explanation page and removed all versions from the market place.

Thanks for reporting

**Comment by marcelhillesheim** [comment]
I uploaded a version with the fix to jetbrains, but they need to accept the update, which takes up to 2 business days. Also removed older versions from the market place.

**Comment by marcelhillesheim** [comment]
Update is available. Closed
